apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: patient-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: SERVICE_NAME
          value: "patient"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongo-patient-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: INTERNAL_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: internal-secret
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rabbitmq-url
        - name: APPOINTMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: APPOINTMENT_SERVICE_URL
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloudinary-cloud-name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloudinary-api-key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloudinary-api-secret
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: ALLOWED_ORIGINS
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: healthcare
spec:
  selector:
    app: patient-service
  ports:
  - port: 3002
    targetPort: 3002